#!/bin/bash
PORTA=9970
ESEGUIBILE="./digestore_guazzo"

while (true)
do
    echo eseguo "$ESEGUIBILE"
    nc.traditional -l -p ${PORTA} -c "$ESEGUIBILE"
done

#nc.traditional crea connessione
#-l dice che sono il server
# -p è la prota
#-c comandi da eseguire
